# Uncomment the next line to define a global platform for your project
platform :macos, '11.0'

target 'PassGarbleMac' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PassGarbleMac
  pod 'pass_garble', :path => '../../'

  #pod 'PassGarble', :git => 'https://github.com/flock-community/pass-garble.git'

#  target 'PassGarbleMacTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'PassGarbleMacUITests' do
#    # Pods for testing
#  end

end

post_install do |installer| # src: https://stackoverflow.com/a/64139830/6003494
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["ONLY_ACTIVE_ARCH"] = "YES"
    end
  end
end
